package com.google.android.gms.fitness;

import com.google.android.gms.location.LocationRequest;
import org.bpmikc.akm.C0615R;

public class FitnessActivities {
    public static final String AEROBICS = "aerobics";
    public static final String BADMINTON = "badminton";
    public static final String BASEBALL = "baseball";
    public static final String BASKETBALL = "basketball";
    public static final String BIATHLON = "biathlon";
    public static final String BIKING = "biking";
    public static final String BIKING_HAND = "biking.hand";
    public static final String BIKING_MOUNTAIN = "biking.mountain";
    public static final String BIKING_ROAD = "biking.road";
    public static final String BIKING_SPINNING = "biking.spinning";
    public static final String BIKING_STATIONARY = "biking.stationary";
    public static final String BIKING_UTILITY = "biking.utility";
    public static final String BOXING = "boxing";
    public static final String CALISTHENICS = "calisthenics";
    public static final String CIRCUIT_TRAINING = "circuit_training";
    public static final String CRICKET = "cricket";
    public static final String CROSSFIT = "crossfit";
    public static final String CURLING = "curling";
    public static final String DANCING = "dancing";
    public static final String DIVING = "diving";
    public static final String ELEVATOR = "elevator";
    public static final String ELLIPTICAL = "elliptical";
    public static final String ERGOMETER = "ergometer";
    public static final String ESCALATOR = "escalator";
    public static final String EXTRA_STATUS = "actionStatus";
    public static final String FENCING = "fencing";
    public static final String FOOTBALL_AMERICAN = "football.american";
    public static final String FOOTBALL_AUSTRALIAN = "football.australian";
    public static final String FOOTBALL_SOCCER = "football.soccer";
    public static final String FRISBEE_DISC = "frisbee_disc";
    public static final String GARDENING = "gardening";
    public static final String GOLF = "golf";
    public static final String GYMNASTICS = "gymnastics";
    public static final String HANDBALL = "handball";
    public static final String HIGH_INTENSITY_INTERVAL_TRAINING = "interval_training.high_intensity";
    public static final String HIKING = "hiking";
    public static final String HOCKEY = "hockey";
    public static final String HORSEBACK_RIDING = "horseback_riding";
    public static final String HOUSEWORK = "housework";
    public static final String ICE_SKATING = "ice_skating";
    public static final String INTERVAL_TRAINING = "interval_training";
    public static final String IN_VEHICLE = "in_vehicle";
    public static final String JUMP_ROPE = "jump_rope";
    public static final String KAYAKING = "kayaking";
    public static final String KETTLEBELL_TRAINING = "kettlebell_training";
    public static final String KICKBOXING = "kickboxing";
    public static final String KICK_SCOOTER = "kick_scooter";
    public static final String KITESURFING = "kitesurfing";
    public static final String MARTIAL_ARTS = "martial_arts";
    public static final String MEDITATION = "meditation";
    public static final String MIME_TYPE_PREFIX = "vnd.google.fitness.activity/";
    public static final String MIXED_MARTIAL_ARTS = "martial_arts.mixed";
    public static final String ON_FOOT = "on_foot";
    public static final String OTHER = "other";
    public static final String P90X = "p90x";
    public static final String PARAGLIDING = "paragliding";
    public static final String PILATES = "pilates";
    public static final String POLO = "polo";
    public static final String RACQUETBALL = "racquetball";
    public static final String ROCK_CLIMBING = "rock_climbing";
    public static final String ROWING = "rowing";
    public static final String ROWING_MACHINE = "rowing.machine";
    public static final String RUGBY = "rugby";
    public static final String RUNNING = "running";
    public static final String RUNNING_JOGGING = "running.jogging";
    public static final String RUNNING_SAND = "running.sand";
    public static final String RUNNING_TREADMILL = "running.treadmill";
    public static final String SAILING = "sailing";
    public static final String SCUBA_DIVING = "scuba_diving";
    public static final String SKATEBOARDING = "skateboarding";
    public static final String SKATING = "skating";
    public static final String SKATING_CROSS = "skating.cross";
    public static final String SKATING_INDOOR = "skating.indoor";
    public static final String SKATING_INLINE = "skating.inline";
    public static final String SKIING = "skiing";
    public static final String SKIING_BACK_COUNTRY = "skiing.back_country";
    public static final String SKIING_CROSS_COUNTRY = "skiing.cross_country";
    public static final String SKIING_DOWNHILL = "skiing.downhill";
    public static final String SKIING_KITE = "skiing.kite";
    public static final String SKIING_ROLLER = "skiing.roller";
    public static final String SLEDDING = "sledding";
    public static final String SLEEP = "sleep";
    public static final String SLEEP_AWAKE = "sleep.awake";
    public static final String SLEEP_DEEP = "sleep.deep";
    public static final String SLEEP_LIGHT = "sleep.light";
    public static final String SLEEP_REM = "sleep.rem";
    public static final String SNOWBOARDING = "snowboarding";
    public static final String SNOWMOBILE = "snowmobile";
    public static final String SNOWSHOEING = "snowshoeing";
    public static final String SQUASH = "squash";
    public static final String STAIR_CLIMBING = "stair_climbing";
    public static final String STAIR_CLIMBING_MACHINE = "stair_climbing.machine";
    public static final String STANDUP_PADDLEBOARDING = "standup_paddleboarding";
    public static final String STATUS_ACTIVE = "ActiveActionStatus";
    public static final String STATUS_COMPLETED = "CompletedActionStatus";
    public static final String STILL = "still";
    public static final String STRENGTH_TRAINING = "strength_training";
    public static final String SURFING = "surfing";
    public static final String SWIMMING = "swimming";
    public static final String SWIMMING_OPEN_WATER = "swimming.open_water";
    public static final String SWIMMING_POOL = "swimming.pool";
    public static final String TABLE_TENNIS = "table_tennis";
    public static final String TEAM_SPORTS = "team_sports";
    public static final String TENNIS = "tennis";
    public static final String TILTING = "tilting";
    public static final String TREADMILL = "treadmill";
    public static final String UNKNOWN = "unknown";
    public static final String VOLLEYBALL = "volleyball";
    public static final String VOLLEYBALL_BEACH = "volleyball.beach";
    public static final String VOLLEYBALL_INDOOR = "volleyball.indoor";
    public static final String WAKEBOARDING = "wakeboarding";
    public static final String WALKING = "walking";
    public static final String WALKING_FITNESS = "walking.fitness";
    public static final String WALKING_NORDIC = "walking.nordic";
    public static final String WALKING_STROLLER = "walking.stroller";
    public static final String WALKING_TREADMILL = "walking.treadmill";
    public static final String WATER_POLO = "water_polo";
    public static final String WEIGHTLIFTING = "weightlifting";
    public static final String WHEELCHAIR = "wheelchair";
    public static final String WINDSURFING = "windsurfing";
    public static final String YOGA = "yoga";
    public static final String ZUMBA = "zumba";
    private static final String[] zzank;

    static {
        zzank = new String[119];
        zzank[9] = AEROBICS;
        zzank[10] = BADMINTON;
        zzank[11] = BASEBALL;
        zzank[12] = BASKETBALL;
        zzank[13] = BIATHLON;
        zzank[1] = BIKING;
        zzank[14] = BIKING_HAND;
        zzank[15] = BIKING_MOUNTAIN;
        zzank[16] = BIKING_ROAD;
        zzank[17] = BIKING_SPINNING;
        zzank[18] = BIKING_STATIONARY;
        zzank[19] = BIKING_UTILITY;
        zzank[20] = BOXING;
        zzank[21] = CALISTHENICS;
        zzank[22] = CIRCUIT_TRAINING;
        zzank[23] = CRICKET;
        zzank[113] = CROSSFIT;
        zzank[C0615R.styleable.Theme_switchStyle] = CURLING;
        zzank[24] = DANCING;
        zzank[LocationRequest.PRIORITY_BALANCED_POWER_ACCURACY] = DIVING;
        zzank[117] = ELEVATOR;
        zzank[25] = ELLIPTICAL;
        zzank[C0615R.styleable.Theme_radioButtonStyle] = ERGOMETER;
        zzank[118] = ESCALATOR;
        zzank[6] = "exiting_vehicle";
        zzank[26] = FENCING;
        zzank[27] = FOOTBALL_AMERICAN;
        zzank[28] = FOOTBALL_AUSTRALIAN;
        zzank[29] = FOOTBALL_SOCCER;
        zzank[30] = FRISBEE_DISC;
        zzank[31] = GARDENING;
        zzank[32] = GOLF;
        zzank[33] = GYMNASTICS;
        zzank[34] = HANDBALL;
        zzank[114] = HIGH_INTENSITY_INTERVAL_TRAINING;
        zzank[35] = HIKING;
        zzank[36] = HOCKEY;
        zzank[37] = HORSEBACK_RIDING;
        zzank[38] = HOUSEWORK;
        zzank[LocationRequest.PRIORITY_LOW_POWER] = ICE_SKATING;
        zzank[0] = IN_VEHICLE;
        zzank[115] = INTERVAL_TRAINING;
        zzank[39] = JUMP_ROPE;
        zzank[40] = KAYAKING;
        zzank[41] = KETTLEBELL_TRAINING;
        zzank[107] = KICK_SCOOTER;
        zzank[42] = KICKBOXING;
        zzank[43] = KITESURFING;
        zzank[44] = MARTIAL_ARTS;
        zzank[45] = MEDITATION;
        zzank[46] = MIXED_MARTIAL_ARTS;
        zzank[2] = ON_FOOT;
        zzank[108] = OTHER;
        zzank[47] = P90X;
        zzank[48] = PARAGLIDING;
        zzank[49] = PILATES;
        zzank[50] = POLO;
        zzank[51] = RACQUETBALL;
        zzank[52] = ROCK_CLIMBING;
        zzank[53] = ROWING;
        zzank[54] = ROWING_MACHINE;
        zzank[55] = RUGBY;
        zzank[8] = RUNNING;
        zzank[56] = RUNNING_JOGGING;
        zzank[57] = RUNNING_SAND;
        zzank[58] = RUNNING_TREADMILL;
        zzank[59] = SAILING;
        zzank[60] = SCUBA_DIVING;
        zzank[61] = SKATEBOARDING;
        zzank[62] = SKATING;
        zzank[63] = SKATING_CROSS;
        zzank[LocationRequest.PRIORITY_NO_POWER] = SKATING_INDOOR;
        zzank[64] = SKATING_INLINE;
        zzank[65] = SKIING;
        zzank[66] = SKIING_BACK_COUNTRY;
        zzank[67] = SKIING_CROSS_COUNTRY;
        zzank[68] = SKIING_DOWNHILL;
        zzank[69] = SKIING_KITE;
        zzank[70] = SKIING_ROLLER;
        zzank[71] = SLEDDING;
        zzank[72] = SLEEP;
        zzank[109] = SLEEP_LIGHT;
        zzank[110] = SLEEP_DEEP;
        zzank[111] = SLEEP_REM;
        zzank[112] = SLEEP_AWAKE;
        zzank[73] = SNOWBOARDING;
        zzank[74] = SNOWMOBILE;
        zzank[75] = SNOWSHOEING;
        zzank[76] = SQUASH;
        zzank[77] = STAIR_CLIMBING;
        zzank[78] = STAIR_CLIMBING_MACHINE;
        zzank[79] = STANDUP_PADDLEBOARDING;
        zzank[3] = STILL;
        zzank[80] = STRENGTH_TRAINING;
        zzank[81] = SURFING;
        zzank[82] = SWIMMING;
        zzank[83] = SWIMMING_POOL;
        zzank[84] = SWIMMING_OPEN_WATER;
        zzank[85] = TABLE_TENNIS;
        zzank[86] = TEAM_SPORTS;
        zzank[87] = TENNIS;
        zzank[5] = TILTING;
        zzank[88] = TREADMILL;
        zzank[4] = UNKNOWN;
        zzank[89] = VOLLEYBALL;
        zzank[90] = VOLLEYBALL_BEACH;
        zzank[91] = VOLLEYBALL_INDOOR;
        zzank[92] = WAKEBOARDING;
        zzank[7] = WALKING;
        zzank[93] = WALKING_FITNESS;
        zzank[94] = WALKING_NORDIC;
        zzank[95] = WALKING_TREADMILL;
        zzank[116] = WALKING_STROLLER;
        zzank[96] = WATER_POLO;
        zzank[97] = WEIGHTLIFTING;
        zzank[98] = WHEELCHAIR;
        zzank[99] = WINDSURFING;
        zzank[100] = YOGA;
        zzank[C0615R.styleable.Theme_checkedTextViewStyle] = ZUMBA;
    }

    FitnessActivities() {
    }

    public static String getMimeType(String activity) {
        return MIME_TYPE_PREFIX + activity;
    }

    public static String getName(int activity) {
        if (activity < 0 || activity >= zzank.length) {
            return UNKNOWN;
        }
        String str = zzank[activity];
        return str == null ? UNKNOWN : str;
    }

    public static int zzcP(String str) {
        for (int i = 0; i < zzank.length; i++) {
            if (zzank[i].equals(str)) {
                return i;
            }
        }
        return 4;
    }
}
